### PR TITLE
Babel transformed classes

### PR DESCRIPTION
**Pull request by geoffdutton**
This only includes the slight modification to spy on babel transformed class methods.

### CODE REVIEW

**Comment by geoffdutton** [comment]
I'm having issues with running the tests, I can't figure out what it is yet. If I run `gulp tdd` or `gulp test`, it takes about 90 seconds to initialize. I'm still looking into this.

Here's the issue I'm facing. When I declare a class like this:

```
/* eslint-disable */
'use strict';

export default class ExampleEs6Class {
  constructor() {

  }
  methodOne() {

  }
  methodTwo() {

  }
}
```

It transforms to the following:

```/* eslint-disable */
'use strict';

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var ExampleEs6Class = function () {
  function ExampleEs6Class() {
    _classCallCheck(this, ExampleEs6Class);
  }

  _createClass(ExampleEs6Class, [{
    key: 'methodOne',
    value: function methodOne() {}
  }, {
    key: 'methodTwo',
    value: function methodTwo() {}
  }]);

  return ExampleEs6Class;
}();

exports.default = ExampleEs6Class;
```

If you just import it normally, `rollup` will complain that the class is never exported because I think it's looking for the es6 style export.

I can get the tests to pass if I remove the 'es2015' option for gulp-babel, but that ends up defeating the purpose of the test. The issue in the real world is that when babel transforms a class with the es2015 option, it doesn't use the tradition prototype way of declaring instance methods, and so `jasmine.spyAll` won't find those.

The solution is to also check to see if `Object.getPrototypeOf` is available, and if so, call that to get the methods to spy on.

I can't get the tests to run properly though. I'm unfamiliar with `rollup`, do you have experience with that?

**Comment by mjeanroy** [comment]
Hi @geoffdutton,

First of all, I'm glad that you not gave up your PR, thank you for that and, again, thank you for you awesome work!

> I can't get the tests to run properly though. I'm unfamiliar with rollup, do you have experience with that?

Yeah, I chose rollup as module bundler as it is, *in my opinion*, one of the best ES6 module bundler available today. The bad side is that it may take some time for karma to preprocess all the files before running any tests, that's why it may take around 90ms before runnin any tests with `npm test` command. The `cache` feature of rollup may help, I'll check if it is.

> it doesn't use the tradition prototype way of declaring instance methods, and so jasmine.spyAll won't find those.

The reason is that I'm using the babel `loose` mode (see the `.babelrc` file). It may change in the future, but currently this is the best way to produce a bundle that can be execute with IE8. I think it is important for a test library to support IE8 for, at least, the next few months. This behavior can be tested by using the `Object.defineProperty` directly.

> If you just import it normally, rollup will complain that the class is never exported because I think it's looking for the es6 style export.

Yeah, rollup need an export with the "classic" ES6 export (just use the standard ES6 `export` and it should be fine). Please, use named exports instead of `default`, my opinion is that it is easier to maintain in the future.

I probably repeat myself, but thank you for the time you spent on this library!

**Comment by geoffdutton** [comment]
Okay now I understand what rollup js is. I just pushed my current proposal. What I'm trying to test is a babel transformed class that isn't used the 'loose' preset, as I ran into that issue in one of my projects.

There's one failing test still, and I'm still thinking through how to address it. When using the 'loose' preset, a for...in will iterate of a transformed class's methods (Klass in this case). Then the Object.getPrototypeOf will return those same methods. Perhaps it's just the order of the for...in loop here? https://github.com/geoffdutton/jasmine-utils/blob/d5dddee139b8e5dec4234c8c1fe331dec87cd665/src/core/spies/for-each-writable-properties.js#L42

**Comment by geoffdutton** [comment]
Weird, I don't know why Travis is saying the checks have passed: https://travis-ci.org/mjeanroy/jasmine-utils/jobs/183101631

**Comment by geoffdutton** [comment]
Okay I've got it working now. A few things:
- I threw out the babel task to transform an ES6 class, and just pulled out the actual pieces I needed per your suggestion.
- I swapped in [karma-rollup-preprocessor](https://www.npmjs.com/package/karma-rollup-preprocessor) and it seems to be starting quicker, and it caches the bundle by default.
- I changed the `foundProps` from an object to a Set, and moved it outside of the while loop. This way, and I add the actual method reference to the Set as we pass them to the iterator. I think it's safer than relying on names. It looks like the babel pollyfill has a Set polyfill?
- I moved the `Object.getPrototypeOf` higher up, and add any properties that finds that we don't already have with the exception of the `constructor` property. My reasoning is that if we have an instantiated object, it's pointless to spy on the constructor then since it will have already been called. Thoughts?

I'd still like to test a few more things like inheritance in non-loose transformed classes, but I think we're in pretty good shape. I'd love for your review and feedback.

Also, I noticed when running `tdd`, the watcher doesn't seem to recognize changes in the `src/` directory. I think it's because those files aren't included in the karm.conf.js `config.files`. I tried added them to be watched by not included, and that threw off an infinite loop as soon as one file changed. Perhaps a single rollup entry file would work? That's what I've done with webpack before. Basically there would be a test_index.js file with something like:
```// test/test_index.js

// require all modules ending in "_test" from the
// current directory and all subdirectories
var testsContext = require.context(".", true, /_test$/);
testsContext.keys().forEach(function(path) {
    try {
        testsContext(path);
    } catch(err) {
        console.error('[ERROR] WITH SPEC FILE: ', path);
        console.error(err);
    }
});```

**Pull request merged**
